DROP TABLE [dbo].[SYS_CONFIG];
GO
CREATE TABLE [dbo].[SYS_CONFIG](
	[ID] [int] IDENTITY(1,1) primary key,
	[NAME] [varchar](100) NOT NULL,
	[VALUE] [varchar](100) NULL,
	[REGEX] [varchar](200) NULL,
	[ENABLE] [int] NULL,
	[DESCRIPTION] [varchar](500) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [varchar](50) NULL
);

GO
DROP TABLE [dbo].[SYS_BASIC_INFO];
GO
CREATE TABLE [dbo].[SYS_BASIC_INFO](
	[ID] [int] IDENTITY(1,1) primary key,
	[TYPE] [varchar](50) NULL,
	[CODE] [varchar](200) NULL,
	[NAME] [varchar](200) NULL,
	[SEQ] [int] NULL,
	[REMARK] [varchar](200) NULL,
	[ENABLE] [char](10) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [varchar](50) NULL
);

GO
DROP TABLE [dbo].[SYS_RESOURCE];
GO
CREATE TABLE [dbo].[SYS_RESOURCE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SORT_ID] [int] NOT NULL,
	[CODE] [varchar](50) NULL,
	[P_CODE] [varchar](50) NULL,
	[TEXT] [varchar](500) NULL,
	[URL] [varchar](50) NULL,
	[TYPE] [char](1) NULL,
	[EXPAND] [char](1) NULL,
	[LEAF] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nchar](10) NULL,
 CONSTRAINT [PK_SYS_MENU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
);
GO

DROP TABLE [dbo].[SYS_USER_INFO];
GO
CREATE TABLE [dbo].[SYS_USER_INFO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_CODE] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[PASSWORD] [varchar](50) NULL,
	[EMAIL] [varchar](500) NULL,
	[LOCKED] [char](1) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nchar](10) NULL,
 CONSTRAINT [PK_SYS_USER_INFO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
DROP TABLE [dbo].[SYS_ROLE];
GO
CREATE TABLE [dbo].[SYS_ROLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_CODE] [varchar](50) NULL,
	[ROLE_NAME] [varchar](500) NULL,
	[REMARK] [varchar](5000) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nchar](10) NULL,
 CONSTRAINT [PK_SYS_ROLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
DROP TABLE [dbo].[SYS_ROLE_RES_RELATION];
GO
CREATE TABLE [dbo].[SYS_ROLE_RES_RELATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ROLE_CODE] [varchar](50) NULL,
	[RES_CODE] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [varchar](50) NULL,
 CONSTRAINT [PK_SYS_ROLE_RES_RELATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
DROP TABLE [dbo].[SYS_USER_ROLE_RELATION];
GO
CREATE TABLE [dbo].[SYS_USER_ROLE_RELATION](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PERSON_CODE] [varchar](50) NULL,
	[ROLE_CODE] [varchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](50) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [varchar](50) NULL,
 CONSTRAINT [PK_SYS_USER_ROLE_RELATION] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[SYS_ICONS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TEXT] [varchar](64) NULL,
	[CODE] [varchar](64) NULL,
	[RESOURCE_ID] [varchar](64) NULL,
	[RESOURCE] [varbinary](max) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [varchar](64) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [varchar](64) NULL,
 CONSTRAINT [PK__OP_ICONS__3214EC2764B7E415] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO