--<ScriptOptions statementTerminator="GO"/>

ALTER TABLE "dbo"."SYS_ROLE_RES_RELATION" DROP CONSTRAINT "PK_SYS_ROLE_RES_RELATION"
GO

ALTER TABLE "dbo"."SYS_RESOURCE" DROP CONSTRAINT "PK_SYS_MENU"
GO

ALTER TABLE "dbo"."SYS_USER_INFO" DROP CONSTRAINT "PK_SYS_USER_INFO"
GO

ALTER TABLE "dbo"."SYS_CONFIG" DROP CONSTRAINT "PK__SYS_CONF__3214EC271FCDBCEB"
GO

ALTER TABLE "dbo"."SYS_BASIC_INFO" DROP CONSTRAINT "PK__SYS_BASI__3214EC27239E4DCF"
GO

ALTER TABLE "dbo"."SYS_USER_ROLE_RELATION" DROP CONSTRAINT "PK_SYS_USER_ROLE_RELATION"
GO

ALTER TABLE "dbo"."SYS_ROLE" DROP CONSTRAINT "PK_SYS_ROLE"
GO

DROP TABLE "dbo"."SYS_CONFIG"
GO

DROP TABLE "dbo"."SYS_BASIC_INFO"
GO

DROP TABLE "dbo"."SYS_ROLE_RES_RELATION"
GO

DROP TABLE "dbo"."SYS_RESOURCE"
GO

DROP TABLE "dbo"."SYS_USER_INFO"
GO

DROP TABLE "dbo"."SYS_USER_ROLE_RELATION"
GO

DROP TABLE "dbo"."SYS_ROLE"
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE "dbo"."SYS_CONFIG" (
	"ID" INT NOT NULL,
	"NAME" VARCHAR(100) NOT NULL,
	"VALUE" VARCHAR(100),
	"REGEX" VARCHAR(200),
	"ENABLE" INT,
	"DESCRIPTION" VARCHAR(500),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" VARCHAR(50),
	CONSTRAINT "PK__SYS_CONF__3214EC271FCDBCEB" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_BASIC_INFO" (
	"ID" INT NOT NULL,
	"TYPE" VARCHAR(50),
	"CODE" VARCHAR(200),
	"NAME" VARCHAR(200),
	"SEQ" INT,
	"REMARK" VARCHAR(200),
	"ENABLE" CHAR(10),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" VARCHAR(50),
	CONSTRAINT "PK__SYS_BASI__3214EC27239E4DCF" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_ROLE_RES_RELATION" (
	"ID" INT NOT NULL,
	"ROLE_CODE" VARCHAR(50),
	"RES_CODE" VARCHAR(50),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" VARCHAR(50),
	CONSTRAINT "PK_SYS_ROLE_RES_RELATION" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_RESOURCE" (
	"ID" INT NOT NULL,
	"SORT_ID" INT NOT NULL,
	"CODE" VARCHAR(50),
	"P_CODE" VARCHAR(50),
	"TEXT" VARCHAR(500),
	"URL" VARCHAR(50),
	"TYPE" CHAR(1),
	"EXPAND" CHAR(1),
	"LEAF" CHAR(1),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" null,
	CONSTRAINT "PK_SYS_MENU" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_USER_INFO" (
	"ID" INT NOT NULL,
	"PERSON_CODE" VARCHAR(50),
	"LAST_NAME" VARCHAR(50),
	"PASSWORD" VARCHAR(50),
	"EMAIL" VARCHAR(500),
	"LOCKED" CHAR(1),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" null,
	CONSTRAINT "PK_SYS_USER_INFO" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_USER_ROLE_RELATION" (
	"ID" INT NOT NULL,
	"PERSON_CODE" VARCHAR(50),
	"ROLE_CODE" VARCHAR(50),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" VARCHAR(50),
	CONSTRAINT "PK_SYS_USER_ROLE_RELATION" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

CREATE TABLE "dbo"."SYS_ROLE" (
	"ID" INT NOT NULL,
	"ROLE_CODE" VARCHAR(50),
	"ROLE_NAME" VARCHAR(500),
	"REMARK" VARCHAR(5000),
	"CREATE_DATE" DATETIME,
	"CREATE_BY" VARCHAR(50),
	"MODIFY_DATE" DATETIME,
	"MODIFY_BY" null,
	CONSTRAINT "PK_SYS_ROLE" PRIMARY KEY ("ID") WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

)
GO

SET ANSI_PADDING OFF
GO

